// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    DocumentView: typeof import('./src/components/DocumentView.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    ModuleTabs: typeof import('./src/components/ModuleTabs.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    SvgIcon: typeof import('./src/features/svg/SvgIcon.vue')['default']
  }
}

export { }
